flowchart LR
  S["Sabueso<br/>Knowledge memory<br/><i>What is known?</i>"]
  P["Praxis<br/>Methodological memory<br/><i>What do we know how to do?</i>"]
  N["DiscoveryProject<br/>Discovery memory<br/><i>What have we learned?</i>"]
  M[MOLI] -.-> S
  M -.-> P
  M -.-> N
